### ISSUE TITLE
Supporting additional sentences

### ISSUE THREAD

**Issue by elpiel** [AeroRust/nmea#54]
There are multiple sentences that are still not implemented in the crate and this is a list of the remaining sentences that we can implement.

Some work has gone into supporting additional sentences - #51

# Contributing

1. Write a comment - Please write a comment for the sentence(s) you'd like to implement and to be mentioned on the task to avoid duplicate implementations.
2. Implement each sentence alongside at least 1 test in its own module using the `nom` crate.
3. Open a PR 🎉

### Tips for contributing

- We suggest you start with a single sentence per PR and get a sense of the `NMEA 0183` crate and protocol
- If you have any questions, just open a Draft PR, so that we can provide you with feedback or answer your questions
- Checkout the GPSD project page for an example to use in your test (https://gpsd.gitlab.io/gpsd/NMEA.html) and any additional information for the given sentences
- Follow the information for the different versions of NMEA 0183 standard given in the GPSD project and implement the parsing for them

### Sources

- https://gpsd.gitlab.io/gpsd/NMEA.html - sentence types in the list below have been taken from here, the gpsd project also includes examples for each sentence
- https://receiverhelp.trimble.com/alloy-gnss/en-us/NMEA-0183messages_MessageOverview.html - Additional overview resource of the NMEA 0183 messages
- [All Identifiers - Manufacturer Mnemonic Codes, and Sentence Formatters List (2013)](https://www.nmea.org/Assets/20130801%200183%20identifier%20list.pdf)

# Sentences
In this curated list you'll find sentence types that have yet to be implemented and tested.
The standard sentences have priority over the rest of the types and less-known sentences.

- [ ] AIS See #46 
### [NMEA Standard Sentences](https://gpsd.gitlab.io/gpsd/NMEA.html#_nmea_standard_sentences)
   - [x] [AAM - Waypoint Arrival Alarm](https://gpsd.gitlab.io/gpsd/NMEA.html#_aam_waypoint_arrival_alarm) @bahelms #62 
   - [ ] [ALM - GPS Almanac Data](https://gpsd.gitlab.io/gpsd/NMEA.html#_alm_gps_almanac_data)
   - [ ] [APA - Autopilot Sentence "A"](https://gpsd.gitlab.io/gpsd/NMEA.html#_apa_autopilot_sentence_a)
   - [ ] [APB - Autopilot Sentence "B"](https://gpsd.gitlab.io/gpsd/NMEA.html#_apb_autopilot_sentence_b)
   - [x] [BOD - Bearing - Waypoint to Waypoint](https://gpsd.gitlab.io/gpsd/NMEA.html#_bod_bearing_waypoint_to_waypoint) (impled in #51) Tests needed @clemarescx #61 
   - [x] [BWC - Bearing & Distance to Waypoint - Great Circle](https://gpsd.gitlab.io/gpsd/NMEA.html#_bwc_bearing_distance_to_waypoint_great_circle)
   - [ ] [BWR - Bearing and Distance to Waypoint - Rhumb Line](https://gpsd.gitlab.io/gpsd/NMEA.html#_bwr_bearing_and_distance_to_waypoint_rhumb_line)
   - [ ] [BWW - Bearing - Waypoint to Waypoint](https://gpsd.gitlab.io/gpsd/NMEA.html#_bww_bearing_waypoint_to_waypoint)
   - [ ] [DBK - Depth Below Keel](https://gpsd.gitlab.io/gpsd/NMEA.html#_dbk_depth_below_keel)
   - [ ] [DBS - Depth Below Surface](https://gpsd.gitlab.io/gpsd/NMEA.html#_dbs_depth_below_surface)
   - [ ] [DBT - Depth below transducer](https://gpsd.gitlab.io/gpsd/NMEA.html#_dbt_depth_below_transducer)
   - [ ] [DCN - Decca Position](https://gpsd.gitlab.io/gpsd/NMEA.html#_dcn_decca_position)
   - [ ] [DPT - Depth of Water](https://gpsd.gitlab.io/gpsd/NMEA.html#_dpt_depth_of_water)
   - [ ] [DTM - Datum Reference](https://gpsd.gitlab.io/gpsd/NMEA.html#_dtm_datum_reference)
   - [ ] [FSI - Frequency Set Information](https://gpsd.gitlab.io/gpsd/NMEA.html#_fsi_frequency_set_information)
   - [ ] [GBS - GPS Satellite Fault Detection](https://gpsd.gitlab.io/gpsd/NMEA.html#_gbs_gps_satellite_fault_detection) (tests needed) #51 
   - [x] [GGA - Global Positioning System Fix Data](https://gpsd.gitlab.io/gpsd/NMEA.html#_gga_global_positioning_system_fix_data)
   - [ ] [GLC - Geographic Position, Loran-C](https://gpsd.gitlab.io/gpsd/NMEA.html#_glc_geographic_position_loran_c)
   - [x] [GLL - Geographic Position - Latitude/Longitude](https://gpsd.gitlab.io/gpsd/NMEA.html#_gll_geographic_position_latitudelongitude)
   - [x] [GNS - Fix data](https://gpsd.gitlab.io/gpsd/NMEA.html#_gns_fix_data)
   - [ ] [GRS - GPS Range Residuals](https://gpsd.gitlab.io/gpsd/NMEA.html#_grs_gps_range_residuals)
   - [ ] [GST - GPS Pseudorange Noise Statistics](https://gpsd.gitlab.io/gpsd/NMEA.html#_gst_gps_pseudorange_noise_statistics)
   - [x] [GSA - GPS DOP and active satellites](https://gpsd.gitlab.io/gpsd/NMEA.html#_gsa_gps_dop_and_active_satellites)
   - [x] [GSV - Satellites in view](https://gpsd.gitlab.io/gpsd/NMEA.html#_gsv_satellites_in_view)
   - [ ] [GTD - Geographic Location in Time Differences](https://gpsd.gitlab.io/gpsd/NMEA.html#_gtd_geographic_location_in_time_differences)
   - [ ] [GXA - TRANSIT Position - Latitude/Longitude](https://gpsd.gitlab.io/gpsd/NMEA.html#_gxa_transit_position_latitudelongitude)
   - [ ] [HDG - Heading - Deviation & Variation](https://gpsd.gitlab.io/gpsd/NMEA.html#_hdg_heading_deviation_variation)
   - [ ] [HDM - Heading - Magnetic](https://gpsd.gitlab.io/gpsd/NMEA.html#_hdm_heading_magnetic)
   - [ ] [HDT - Heading - True](https://gpsd.gitlab.io/gpsd/NMEA.html#_hdt_heading_true)
   - [ ] [HFB - Trawl Headrope to Footrope and Bottom](https://gpsd.gitlab.io/gpsd/NMEA.html#_hfb_trawl_headrope_to_footrope_and_bottom)
   - [ ] [HSC - Heading Steering Command](https://gpsd.gitlab.io/gpsd/NMEA.html#_hsc_heading_steering_command)
   - [ ] [HWBIAS - Unknown](https://gpsd.gitlab.io/gpsd/NMEA.html#_hwbias_unknown)
   - [ ] [ITS - Trawl Door Spread 2 Distance](https://gpsd.gitlab.io/gpsd/NMEA.html#_its_trawl_door_spread_2_distance)
   - [ ] [LCD - Loran-C Signal Data](https://gpsd.gitlab.io/gpsd/NMEA.html#_lcd_loran_c_signal_data)
   - [ ] [MDA - Meteorological Composite](https://gpsd.gitlab.io/gpsd/NMEA.html#_mda_meteorological_composite)
   - [ ] [MSK - Control for a Beacon Receiver](https://gpsd.gitlab.io/gpsd/NMEA.html#_msk_control_for_a_beacon_receiver)
   - [ ] [MSS - Beacon Receiver Status](https://gpsd.gitlab.io/gpsd/NMEA.html#_mss_beacon_receiver_status)
   - [ ] [MTW - Mean Temperature of Water](https://gpsd.gitlab.io/gpsd/NMEA.html#_mtw_mean_temperature_of_water)
   - [ ] [MWV - Wind Speed and Angle](https://gpsd.gitlab.io/gpsd/NMEA.html#_mwv_wind_speed_and_angle)
   - [ ] [OLN - Omega Lane Numbers](https://gpsd.gitlab.io/gpsd/NMEA.html#_oln_omega_lane_numbers)
   - [ ] [OSD - Own Ship Data](https://gpsd.gitlab.io/gpsd/NMEA.html#_osd_own_ship_data)
   - [ ] [R00 - Waypoints in active route](https://gpsd.gitlab.io/gpsd/NMEA.html#_r00_waypoints_in_active_route)
   - [ ] [RLM – Return Link Message](https://gpsd.gitlab.io/gpsd/NMEA.html#_rlm_return_link_message)
   - [ ] [RMA - Recommended Minimum Navigation Information](https://gpsd.gitlab.io/gpsd/NMEA.html#_rma_recommended_minimum_navigation_information)
   - [ ] [RMB - Recommended Minimum Navigation Information](https://gpsd.gitlab.io/gpsd/NMEA.html#_rmb_recommended_minimum_navigation_information)
   - [x] [RMC - Recommended Minimum Navigation Information](https://gpsd.gitlab.io/gpsd/NMEA.html#_rmc_recommended_minimum_navigation_information)
   - [ ] [ROT - Rate Of Turn](https://gpsd.gitlab.io/gpsd/NMEA.html#_rot_rate_of_turn)
   - [ ] [RPM - Revolutions](https://gpsd.gitlab.io/gpsd/NMEA.html#_rpm_revolutions)
   - [ ] [RSA - Rudder Sensor Angle](https://gpsd.gitlab.io/gpsd/NMEA.html#_rsa_rudder_sensor_angle)
   - [ ] [RSD - RADAR System Data](https://gpsd.gitlab.io/gpsd/NMEA.html#_rsd_radar_system_data)
   - [ ] [RTE - Routes](https://gpsd.gitlab.io/gpsd/NMEA.html#_rte_routes)
   - [ ] [SFI - Scanning Frequency Information](https://gpsd.gitlab.io/gpsd/NMEA.html#_sfi_scanning_frequency_information)
   - [ ] [STN - Multiple Data ID](https://gpsd.gitlab.io/gpsd/NMEA.html#_stn_multiple_data_id)
   - [ ] [TDS - Trawl Door Spread Distance](https://gpsd.gitlab.io/gpsd/NMEA.html#_tds_trawl_door_spread_distance)
   - [ ] [TFI - Trawl Filling Indicator](https://gpsd.gitlab.io/gpsd/NMEA.html#_tfi_trawl_filling_indicator)
   - [ ] [TLB - Target Label](https://gpsd.gitlab.io/gpsd/NMEA.html#_tlb_target_label)
   - [ ] [TLL - Target Latitude and Longitude](https://gpsd.gitlab.io/gpsd/NMEA.html#_tll_target_latitude_and_longitude)
   - [ ] [TPC - Trawl Position Cartesian Coordinates](https://gpsd.gitlab.io/gpsd/NMEA.html#_tpc_trawl_position_cartesian_coordinates)
   - [ ] [TPR - Trawl Position Relative Vessel](https://gpsd.gitlab.io/gpsd/NMEA.html#_tpr_trawl_position_relative_vessel)
   - [ ] [TPT - Trawl Position True](https://gpsd.gitlab.io/gpsd/NMEA.html#_tpt_trawl_position_true)
   - [ ] [TRF - TRANSIT Fix Data](https://gpsd.gitlab.io/gpsd/NMEA.html#_trf_transit_fix_data)
   - [ ] [TTM - Tracked Target Message](https://gpsd.gitlab.io/gpsd/NMEA.html#_ttm_tracked_target_message)
   - [ ] [VBW - Dual Ground/Water Speed](https://gpsd.gitlab.io/gpsd/NMEA.html#_vbw_dual_groundwater_speed)
   - [ ] [VDR - Set and Drift](https://gpsd.gitlab.io/gpsd/NMEA.html#_vdr_set_and_drift)
   - [ ] [VHW - Water speed and heading](https://gpsd.gitlab.io/gpsd/NMEA.html#_vhw_water_speed_and_heading)
   - [ ] [VLW - Distance Traveled through Water](https://gpsd.gitlab.io/gpsd/NMEA.html#_vlw_distance_traveled_through_water)
   - [ ] [VPW - Speed - Measured Parallel to Wind](https://gpsd.gitlab.io/gpsd/NMEA.html#_vpw_speed_measured_parallel_to_wind)
   - [x] [VTG - Track made good and Ground speed](https://gpsd.gitlab.io/gpsd/NMEA.html#_vtg_track_made_good_and_ground_speed)
   - [ ] [VWR - Relative Wind Speed and Angle](https://gpsd.gitlab.io/gpsd/NMEA.html#_vwr_relative_wind_speed_and_angle)
   - [ ] [WCV - Waypoint Closure Velocity](https://gpsd.gitlab.io/gpsd/NMEA.html#_wcv_waypoint_closure_velocity)
   - [ ] [WNC - Distance - Waypoint to Waypoint](https://gpsd.gitlab.io/gpsd/NMEA.html#_wnc_distance_waypoint_to_waypoint)
   - [ ] [WPL - Waypoint Location](https://gpsd.gitlab.io/gpsd/NMEA.html#_wpl_waypoint_location)
   - [ ] [XDR - Transducer Measurement](https://gpsd.gitlab.io/gpsd/NMEA.html#_xdr_transducer_measurement)
   - [ ] [XTE - Cross-Track Error, Measured](https://gpsd.gitlab.io/gpsd/NMEA.html#_xte_cross_track_error_measured)
   - [ ] [XTR - Cross Track Error - Dead Reckoning](https://gpsd.gitlab.io/gpsd/NMEA.html#_xtr_cross_track_error_dead_reckoning)
   - [ ] [ZDA - Time & Date - UTC, day, month, year and local time zone](https://gpsd.gitlab.io/gpsd/NMEA.html#_zda_time_date_utc_day_month_year_and_local_time_zone)
   - [ ] [ZFO - UTC & Time from origin Waypoint](https://gpsd.gitlab.io/gpsd/NMEA.html#_zfo_utc_time_from_origin_waypoint)
   - [ ] [ZTG - UTC & Time to Destination Waypoint](https://gpsd.gitlab.io/gpsd/NMEA.html#_ztg_utc_time_to_destination_waypoint)
### [Other sentences](https://gpsd.gitlab.io/gpsd/NMEA.html#_other_sentences)  **(low priority)**
   - TODO: Find information on the internet for those additional messages if possible 
   - [x] TXT (u-blox)
   - [ ] ACK - Alarm Acknowledgement
   - [ ] ADS - Automatic Device Status
   - [ ] AKD - Acknowledge Detail Alarm Condition
   - [ ] ALA - Set Detail Alarm Condition
   - [ ] ASD - Autopilot System Data
   - [ ] BEC - Bearing & Distance to Waypoint - Dead Reckoning
   - [ ] CEK - Configure Encryption Key Command
   - [ ] COP - Configure the Operational Period, Command
   - [ ] CUR - Water Current Layer
   - [ ] DCR - Device Capability Report
   - [ ] DDC - Display Dimming Control
   - [ ] DOR - Door Status Detection
   - [ ] DSC - Digital Selective Calling Information
   - [ ] DSE - Extended DSC
   - [ ] DSI - DSC Transponder Initiate
   - [ ] DSR - DSC Transponder Response
   - [ ] ETL - Engine Telegraph Operation Status
   - [ ] EVE - General Event Message
   - [ ] FIR - Fire Detection
   - [ ] MWD - Wind Direction & Speed
   - [ ] WDR - Distance to Waypoint - Rhumb Line
   - [ ] WDC - Distance to Waypoint - Great Circle
   - [ ] ZDL - Time and Distance to Variable Point
### [Vendor extensions](https://gpsd.gitlab.io/gpsd/NMEA.html#_vendor_extensions) **(low priority)**
   - [ ] [PASHR - RT300 proprietary roll and pitch sentence](https://gpsd.gitlab.io/gpsd/NMEA.html#_pashr_rt300_proprietary_roll_and_pitch_sentence)
   - [ ] [PGLOR - Quectel](https://gpsd.gitlab.io/gpsd/NMEA.html#_pglor_quectel)
   - [ ] [PGRME - Garmin Estimated Error](https://gpsd.gitlab.io/gpsd/NMEA.html#_pgrme_garmin_estimated_error)
   - [x] [PGRMZ - Garmin Altitude](https://gpsd.gitlab.io/gpsd/NMEA.html#_pgrmz_garmin_altitude) #59 
   - [ ] [PJLTS - Jackson Labs GPSDO Status](https://gpsd.gitlab.io/gpsd/NMEA.html#_pjlts_jackson_labs_gpsdo_status)
   - [ ] [PJLTS - Jackson Labs Time and 3D velocity](https://gpsd.gitlab.io/gpsd/NMEA.html#_pjlts_jackson_labs_time_and_3d_velocity)
   - [ ] [PMGNST - Magellan Status](https://gpsd.gitlab.io/gpsd/NMEA.html#_pmgnst_magellan_status)
   - [ ] [PRWIZCH - Rockwell Channel Status](https://gpsd.gitlab.io/gpsd/NMEA.html#_prwizch_rockwell_channel_status)
   - [ ] [PUBX 00 - u-blox Lat/Long Position Data](https://gpsd.gitlab.io/gpsd/NMEA.html#_pubx_00_u_blox_latlong_position_data)
   - [ ] [PUBX 01 - u-blox UTM Position Data](https://gpsd.gitlab.io/gpsd/NMEA.html#_pubx_01_u_blox_utm_position_data)
   - [ ] [PUBX 03 - u-blox Satellite Status](https://gpsd.gitlab.io/gpsd/NMEA.html#_pubx_03_u_blox_satellite_status)
   - [ ] [PUBX 04 - u-blox Time of Day and Clock Information](https://gpsd.gitlab.io/gpsd/NMEA.html#_pubx_04_u_blox_time_of_day_and_clock_information)
   - [ ] [TMVTD - Transas VTS / SML tracking system report](https://gpsd.gitlab.io/gpsd/NMEA.html#_tmvtd_transas_vts_sml_tracking_system_report)

**Comment by bahelms** [comment]
Hello! I'd like to give `AAM - Waypoint Arrival Alarm` a shot.

**Comment by clemarescx** [comment]
I wrote 2 tests for `BOD - Bearing - Waypoint to Waypoint (tests needed)` and presumably fixed an error in BOD parsing, can I send the PR for review?

**Comment by elpiel** [comment]
> 



> I wrote 2 tests for `BOD - Bearing - Waypoint to Waypoint (tests needed)` and presumably fixed an error in BOD parsing, can I send the PR for review?

Of course, you can. I will add it as a task and assign it to you.

**Comment by bahelms** [comment]
@elpiel I have a question about the AAM sentence. I see that `Nmea::parse` does not support all sentences. It would seem AAM should also not be supported here based on the docs:
```
    /// Parse any NMEA sentence and stores the result of sentences that include:
    /// - altitude
    /// - latitude and longitude
    /// - speed_over_ground
    /// - and other
    ///
    /// The type of sentence is returned if implemented and valid.
    pub fn parse(&mut self, sentence: &'a str) -> Result<SentenceType, Error<'a>> {
Is this correct?

**Comment by ekuinox** [comment]
Hello! I wanna try to implement parser for HDT sentence.

**Comment by elpiel** [comment]
> Hello! I wanna try to implement parser for HDT sentence.

Great to hear this @ekuinox , I'm adding you on this sentence them 😋

**Comment by ekuinox** [comment]
I'd like to work on ZDA and VHW. 😄

**Comment by elpiel** [comment]
> I'd like to work on ZDA and VHW. smile

They are both yours 😋 have fun implementing them

**Comment by taavit** [comment]
I'd like to pick BWW.

**Comment by elpiel** [comment]
> I'd like to pick BWW, ZFO and ZTG.

Thank you for your interest to contribute to the `nmea` crate!
I have assigned those messages to you.

**Comment by rafiramadhana** [comment]
I'd like to pick [DBS - Depth Below Surface](https://gpsd.gitlab.io/gpsd/NMEA.html#_dbs_depth_below_surface).

**Comment by elpiel** [comment]
Thanks for your interest to contribute @rafiramadhana!
I'm assigning you to the sentence parsing :yum:

**Comment by Tsuiban** [comment]
I'd like to take a swing at VWT (True wind speed and angle).

**Comment by elpiel** [comment]
Great to hear that @Tsuiban!
I've assigned you to the sentence

**Comment by elpiel** [comment]
@Tsuiban are you still interested in working on VWT sentence?

**Comment by mgrouch** [comment]
There is this list of sentences as json. 
I think it could be just used to generate code of all parsers

https://github.com/SmartBoatInnovations/ha-smart0183/blob/main/custom_components/smart0183/Smart0183.json

**Comment by elpiel** [comment]
Thank you for sharing this resource @mgrouch!
Although we could generate the sentences from the JSON, it will rather be used as another source of information for sentences.

Writing these parsers and generating them from the JSON might take more time than what's worth.

What we still need to support is Rust Struct to NMEA sentence and the iterator based parser, as top priority right now

**Comment by zhrbrk** [comment]
Hello, I'd like to work on GST.

**Comment by elpiel** [comment]
> Hello, I'd like to work on GST.

Great to hear that @zhrbrk !
I'm assigning you to the sentence in the list.

**Comment by Tapped** [comment]
Hi, I added support for TTM here: https://github.com/AeroRust/nmea/pull/128

**Comment by trkohler** [comment]
started to work on [DPT - Depth of Water](https://gpsd.gitlab.io/gpsd/NMEA.html#_dpt_depth_of_water)

**Comment by trkohler** [comment]
I'd also pick DBT ([Depth below transducer](https://gpsd.gitlab.io/gpsd/NMEA.html#_dbt_depth_below_transducer)) because in the PR for DPT (#132) had a lot of mistakes with DPT vs DBT spelling... Want to close internal conflict

**Comment by asnimansari** [comment]
@elpiel I would like to pick DBS.

**Comment by asnimansari** [comment]
@elpiel please review this PR to enable DBS.
https://github.com/AeroRust/nmea/pull/138
